### ISSUE TITLE
Duplicate databases created on setup

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dm_log#16]
`rails db:create` generates two databases and (I think) should only generate one.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/189604742569425/198377578195867)

**Comment by bonniegee** [comment]
Hmm, I've heard that rails db:create can be buggy. Can you provide more info about this issue? The solution might be to manually create the database.

**Comment by helrond** [comment]
I think this has to do with your database config in `config\database.yml`. I'm guessing these are defaults, and I'm not sure they're _wrong_ per se, but it would be good to check with an expert.
