### ISSUE TITLE
Auto-populate digital media ID on page load

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dm_log#17]
Currently the id is populated when the user clicks the "Find in ArchivesSpace" button. Would be better if this was populated on the page load.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/189604742569425/198377577965326)

**Comment by bonniegee** [comment]
Can you help me with this? I was running into JavaScript issues.

**Comment by helrond** [comment]
Sure!
