### ISSUE TITLE
Make digital media ID non-editable on edit form

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dm_log#18]
Either hide this field (make it a hidden input) or make it text that cannot be edited.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/189604742569425/198377576967447)

**Comment by bonniegee** [comment]
I don't want to hide the field, because the end user needs to see this ID.

**Comment by bonniegee** [comment]
I would rather have this field be editable, because when creating a new record a user may need or want to edit the ID. On the edit form, this should not be editable--I guess this would be done using JS?

**Comment by helrond** [comment]
Probably? I want to talk to you about the use cases a bit more though.

**Comment by helrond** [comment]
Would a solution like this be preferable? http://stackoverflow.com/questions/18182346/rails-best-way-to-conditionally-show-hide-a-form-field
