### ISSUE TITLE
Show required fields in new item form

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dm_log#19]
User should be able to tell which fields are required before they submit the form and get the error message.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/189604742569425/198381195359071)

**Comment by bonniegee** [comment]
Is there a better (boostrap-ier?) way of doing this than adding red asterisks to the field labels?

**Comment by helrond** [comment]
There's a couple of options (might be a step 1, step 2 thing):
1. Add a required attribute: http://www.w3schools.com/tags/att_input_required.asp. Not pretty but will stop the user and is cross-browser compatible
2. Use some JS validation and http://getbootstrap.com/css/#forms-control-validation for prettier user feedback.

**Comment by bonniegee** [comment]
This is related to issue #1
