### ISSUE TITLE
Display search term(s)

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dm_log#20]
When a user searches, the term they searched for should be displayed somewhere on the page.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/189604742569425/198381194497639)

**Comment by bonniegee** [comment]
It's in the search box--where else should it be?

**Comment by helrond** [comment]
I mean, I'll just say that I didn't notice that. I think this is also related to #21

**Comment by bonniegee** [comment]
Hm, right now this just works as a filter and I'd rather tackle this by creating an actually functional search (see #12 )
