### ISSUE TITLE
Add "view record" link to index page

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dm_log#23]
Wondering if it makes sense to allow users to view individual records (in addition to being able to edit them)? Not sure if there's a use case for this, but if all the data isn't represented in the table I would think there would be. Also allows you to link to a particular item, which could be handy.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/189604742569425/198386605559842)

**Comment by bonniegee** [comment]
This is possible, but not linked to from the main list.
