### ISSUE TITLE
Add PATCH requests to API

### ISSUE THREAD

**Issue by a-berish** [RockefellerArchiveCenter/dm_log#34]
Returns the following error when sending POST and PATCH requests:

`ActionController::RoutingError (No route matches [POST] "dm_items/4/json")`
`ActionController::RoutingError (No route matches [PATCH] "dm_items/4/json")`

**Comment by p-galligan** [comment]
Where is routing handled in the application? Do you have a routes.rb file? My guess is that the HTML generated has an incorrect action.

**Comment by bonniegee** [comment]
I think we need to tackle #46 and then revisit this issue if necessary.
