### ISSUE TITLE
Import from spreadsheet?

### ISSUE THREAD

**Issue by bmrgoldman** [RockefellerArchiveCenter/dm_log#35]
I really appreciate you building this plugin and sharing with the community. I'm looking at using it here at Penn State, but one thing I was wondering was how I might implement it given my current log of hundreds of media items currently found in a Google spreadsheet. Which got me thinking it would be awesome if I could import that. Please consider this a humble suggestion rather than an actual request! Best, Ben

**Comment by bonniegee** [comment]
Thanks, Ben! I had imported our legacy data from a spreadsheet using these instructions: https://gist.github.com/arjunvenkat/1115bc41bf395a162084

as well as a seeds.rb file that looks like this:

```
require 'csv'

csv_text = File.read(Rails.root.join('lib', 'seeds', 'dm_items.csv'))
csv = CSV.parse(csv_text, :headers => true, :encoding => 'UTF-8')
csv.each do |row|
  t = DmItem.new
  t.auto_id = row['auto_id']
  t.format = row['format']
  t.status = row['status']
  t.method = row['method']
  t.disposition = row['disposition']
  t.transfer_date = row['transfer_date']
  t.refid = row['ref_id']
  t.display_title = row['display_title']
  t.resource = row['resource']
  t.save
  puts "#{t.auto_id}, #{t.resource} saved"
end


puts "There are now #{DmItem.count} rows in the digital media items table"
```
I will add a version of these instructions to the README - thanks for pointing this out!

**Comment by bmrgoldman** [comment]
Perfect! Thanks much, Bonnie...
