### ISSUE TITLE
Log virus checking for each dm item

### ISSUE THREAD

**Issue by a-berish** [RockefellerArchiveCenter/dm_log#44]
**Is your feature request related to a problem? Please describe.**
It is difficult to keep track of which digital media items have been virus checked - and whether or not the virus check was successful, failed due to errors/corrupted files, or failed due to viruses found.

**Describe the solution you'd like**
Add another section for each digital media item in a similar fashion the "Transferred" section. We could name this section something along the lines of "Virus Checking Status." 

The default selection should be "Not Checked" with other options:
"Checked - Success"
"Checked - Failed" 

It would also be useful to add a date section that would auto-populate when the "Virus Checking Status" is changed by the user.

**Describe alternatives you've considered**
Currently, we are tracking virus checking by keeping detailed notes, and looking for the existence of the scan.txt file within each disk image folder. This works for now, but with more people participating in imaging and virus checking, this could become more complicated. 

**Additional context**
 Adding this feature could also help us calculate statistics for board books/program plans.

**Comment by p-galligan** [comment]
@bonniegee Should this be a required field?

**Comment by bonniegee** [comment]
@a-berish What do you think?

**Comment by a-berish** [comment]
@p-galligan I'm thinking it should be required. Could we have the virus checking field similar to the "Transfer status" field, where it automatically defaults to Not Scanned (instead of Not Transferred)
