### ISSUE TITLE
Docker-compose build fails

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/dm_log#53]
**Describe the bug**
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y nodejs                        vim                        mysql-client                        --no-install-recommends &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**To Reproduce**
Try to perform a clean docker-compose build

**Expected behavior**
Everything to build correctly

**Error message or screenshots**
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y nodejs                        vim                        mysql-client                        --no-install-recommends &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Impact on your work**
Docker installation no longer works 

**Additional context**
https://stackoverflow.com/questions/55386246/w-failed-to-fetch-http-deb-debian-org-debian-dists-jessie-updates-main-binary

**Comment by helrond** [comment]
This may be a good point to consider updating the Ruby version (the `FROM ruby: 2.3.0` line is what's pulling the Debian dist).

**Comment by p-galligan** [comment]
Yeah, from what I can understand, this is happening because it's Debian 8 and not Debian 9. Using a newer ruby version that pulls from Debian 9 would fix this.

**Comment by helrond** [comment]
You may also want to consider using a non-Ruby base image, since this code is deployed on a CentOS server: https://hub.docker.com/r/centos/ruby-23-centos7
